### ISSUE TITLE
[URGENT] Add Github Sponsorship options and/or FUNDING.yml

### ISSUE THREAD

**Issue by zudsniper** [tf2-automatic/tf2-automatic#107]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Is your feature request related to a problem? Please describe.

My feature is not related to a lack of functionality

### Describe the solution you'd like

- Add `FUNDING.yml` with ko-fi, & probably add a redirect to your trade link for tf item donations!  
- If not legally dubious, join the Github Sponsorship Program!

> _You do amazing work -- let us support it!_ C:  
> -- [@zod](https://github.com/zudsniper)  

### Describe alternatives you've considered

Well I could donate to him some other way... but wait, no I can't! 

### Additional context

> _Nicklason official unofficial fan club opening soon_  

also have a lovely day to anyone reading this... but ESPECIALLY if you're @Nicklason

**Comment by Nicklason** [comment]
This could be added later on but right now the project is not at a point where it is fair to ask for donations. If people want to support the work I do, then giving feedback and suggestions would be very much appreciated.
