### ISSUE TITLE
Save api key instead of checking Steam

### ISSUE THREAD

**Issue by Hhanuska** [tf2-automatic/tf2-automatic#345]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Is your feature request related to a problem? Please describe.

Due to recent Steam changes api keys are no longer visible on https://steamcommunity.com/dev/apikey.

They can only be seen once, on creation.

This results in the bot thinking it's api key is `00000000000000000000000000000000`

### Describe the solution you'd like

Either add an ENV value where the api key must be provided or create a new key on first startup and save that.

### Describe alternatives you've considered

-

**Comment by Nicklason** [comment]
I wanted to create new API keys but I kept getting rate limited so I just made it possible to set the API key using env vars.
