### ISSUE TITLE
Adding desired listing: The operation was unable to achieve a quorum during its retry window

### ISSUE THREAD

**Issue by ZeusJunior** [tf2-automatic/tf2-automatic#401]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Expected behavior

When I send a request to add a desired listing I should receive no 500 error

### Actual behavior

![image](https://github.com/user-attachments/assets/ae409f80-349c-47ae-b63b-a4a9a8daab00)

The second WARN log doesn't always show up with every ERROR log of the same kind, only noticed that one just now

### Steps to reproduce

Semi spam requests to the manager for different items, it should pop up eventually. I'm getting this every couple minutes

### TF2 Automatic version

7.3.1

### Projects

- [ ] @tf2-automatic/bot
- [ ] @tf2-automatic/bot-manager
- [ ] @tf2-automatic/bot-data
- [ ] @tf2-automatic/bot-manager-data
- [X] @tf2-automatic/bptf-manager
- [ ] @tf2-automatic/bptf-manager-data
- [ ] Other (see below)

**Comment by Nicklason** [comment]
We can add config options to adjust the locking timings to maybe fix the issue. The the locking errors are not that big of a problem when they happen during a job that will just be retried when it fails, but it is annoying to see the error fill up the log.

**Comment by ZeusJunior** [comment]
You've already seen it but for clarity I'll add it here too, it's not only the bptf manager that's throwing errors on its own but its also returning it in my app 
![image](https://github.com/user-attachments/assets/3d8159ea-6cdb-4c95-bee4-3485a47a4bea)
